POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "2nd note with user id", 
    "important": true,
    "userId": "68d59c1e60fb3f85eef2e512"
}
###
GET http://localhost:3001/api/notes
###
DELETE http://localhost:3001/api/notes/68cd61e4982a43ec314667dc
###
PUT http://localhost:3001/api/notes/68cd7dd71db7806494081334
Content-Type: application/json

{
    "content": "Changing this note",
    "important": false
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukainen",
    "password": "salainen"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OGQ1OWMxZTYwZmIzZjg1ZWVmMmU1MTIiLCJpYXQiOjE3NTg5MDQxMTh9.d0AT6l8GIhtbaeSxfZuykgV-La1luZgUri0Utz3D7k4

{
    "content": "single page apps use token based auth",
    "important": false
}